"""Build-time submodule revisions. Auto-generated by setup.py."""
PICOQUIC_SHA      = 'd6c5653d0a4fd03a9308541af0052a5bac871407'
PICOQUIC_DESCRIBE = 'd6c5653d'
PICOQUIC_DATE     = '2026-06-05 19:46:20 -0700'
PICOQUIC_SUBJECT  = 'Merge pull request #2107 from rwl4/master'
PICOTLS_SHA       = 'f350eab60742138ac62b42ee444adf04c7898b0d'
PICOTLS_DESCRIBE  = 'f350eab'
PICOTLS_DATE      = '2025-07-16 15:55:42 +0900'
PICOTLS_SUBJECT   = 'Merge pull request #574 from h2o/kazuho/pr570'
