"""Cross-implementation interop tests for aiopquic.

Drives aiopquic against independent QUIC stacks to catch protocol
deviations testing-against-picoquic alone would miss:

  - qh3       (Python; same TLS lineage, different transport)
  - aioquic   (Python; reference asyncio QUIC)
  - ngtcp2    (C; canonical reference, gnutls/openssl — optional, local-only)

Each test exercises both directions: aiopquic-as-client and
aiopquic-as-server. Pass criteria are byte conservation across the
transfer (CRC32 of generated bytes == CRC32 of received bytes) and
sustained throughput above a per-target floor.
"""
