"""aiopquic ↔ picoquicdemo (in-tree native reference peer).

picoquicdemo is the reference client/server shipped with the vendored
picoquic — h09 (hq-interop) and h3/WebTransport from one binary. It
drives aiopquic from the other side of the socket with the exact
library we embed, making it the canonical transport validator (and,
later, the validator for single-port ALPN dispatch).

h09 protocol: client sends ``GET /N\r\n`` on a bidi stream and FINs;
the server responds with exactly N generated bytes and FINs.

Requires the native build (./build.sh builds picoquicdemo). Marked
``native`` so the CI picoquic tier runs it.
"""
import asyncio
import os
import subprocess
import time

import pytest

from aiopquic.asyncio import connect, serve
from aiopquic.asyncio.protocol import QuicConnectionProtocol
from aiopquic.quic.configuration import QuicConfiguration
from aiopquic.quic.events import StreamDataReceived

from .conftest import CERT_FILE, KEY_FILE, _free_port, counted_pad

BINARY = os.path.abspath(os.path.join(
    os.path.dirname(__file__), "..", "..",
    "third_party", "picoquic", "build", "picoquicdemo"))
ALPN = "hq-interop"

pytestmark = [
    pytest.mark.asyncio,
    pytest.mark.native,
    pytest.mark.skipif(
        not os.path.exists(BINARY),
        reason="picoquicdemo not built — run ./build.sh"),
]


# ---------------------------------------------------------------------------
# aiopquic-as-client → picoquicdemo-as-server:
#   h09 GET of a generated document; verifies handshake, RX byte count,
#   and clean FIN handling against the reference server.
# ---------------------------------------------------------------------------

class _H09Client(QuicConnectionProtocol):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.received = bytearray()
        self.done = asyncio.get_event_loop().create_future()

    def quic_event_received(self, event):
        if isinstance(event, StreamDataReceived):
            self.received += event.data
            if event.end_stream and not self.done.done():
                self.done.set_result(True)


@pytest.mark.parametrize("doc_bytes", [1_000_000, 10_000_000])
async def test_aiopquic_client_demo_server_get(cert_paths, doc_bytes):
    port = _free_port()
    server = subprocess.Popen(
        [BINARY, "-p", str(port),
         "-c", cert_paths["cert"], "-k", cert_paths["key"]],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    try:
        time.sleep(0.8)   # demo binds its UDP socket at startup
        cfg = QuicConfiguration(
            is_client=True, alpn_protocols=[ALPN],
            verify_mode=__import__("ssl").CERT_NONE)
        async with connect("127.0.0.1", port, configuration=cfg,
                           create_protocol=_H09Client) as client:
            sid = client._quic.get_next_available_stream_id()
            client._quic.send_stream_data(
                sid, f"GET /{doc_bytes}\r\n".encode(), end_stream=True)
            async with asyncio.timeout(60):
                await client.done
            assert len(client.received) == doc_bytes
    finally:
        server.kill()
        server.wait(timeout=5)


# ---------------------------------------------------------------------------
# picoquicdemo-as-client → aiopquic-as-server:
#   the demo client fetches generated documents from a minimal h09
#   server built on aiopquic; exit code 0 = all scenario streams
#   completed with the full document received.
# ---------------------------------------------------------------------------

_DOC_BYTES = 200_000   # fits the per-stream TX ring in one send


class _H09Server(QuicConnectionProtocol):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._requests = {}
        self._answered = set()

    def quic_event_received(self, event):
        if not isinstance(event, StreamDataReceived):
            return
        buf = self._requests.setdefault(event.stream_id, bytearray())
        buf += event.data
        if event.stream_id in self._answered or b"\n" not in buf:
            return
        line = bytes(buf).split(b"\n", 1)[0].strip()
        # "GET /N" → N generated bytes
        n = int(line.split(b"/", 1)[1]) if b"/" in line else 0
        self._answered.add(event.stream_id)
        self._quic.send_stream_data(
            event.stream_id, counted_pad(n), end_stream=True)


async def test_demo_client_aiopquic_server_get(cert_paths):
    port = _free_port()
    cfg = QuicConfiguration(is_client=False, alpn_protocols=[ALPN])
    cfg.load_cert_chain(cert_paths["cert"], cert_paths["key"])
    server = await serve("127.0.0.1", port, configuration=cfg,
                         create_protocol=_H09Server)
    try:
        # Three concurrent streams — multi-stream scheduling, not just
        # a single-transfer smoke.
        scenario = ";".join(
            f"{i * 4}:/{_DOC_BYTES}" for i in range(3))
        proc = subprocess.run(
            [BINARY, "-D", "-a", ALPN, "127.0.0.1", str(port), scenario],
            capture_output=True, text=True, timeout=60)
        assert proc.returncode == 0, (
            f"picoquicdemo client failed rc={proc.returncode}\n"
            f"stdout:\n{proc.stdout[-2000:]}\nstderr:\n{proc.stderr[-2000:]}")
    finally:
        server.close()
